### ISSUE TITLE
analytics endpoint stopped

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#103]
The Analytics endpoint has stopped working; it hasn't been updated since 7/31: 

```
{
    _id: "597f0664cf5cee04001ae199",
    date: "2017-07-31T10:28:52.542Z",
    count: 3332,
    sensor_count: 73,
    provider_count: 71,
    __v: 0
}
```

When running the calculation of how many images are in the system, current count should be 3,390 (this is a collection count in the mongodb). 

Need look further at the logs in Heroku.

**Comment by tombh** [comment]
This is on production yes? First thing I would try is just a restart of the app. Anlaytics never got any tests written for it, so this probably happened by 'fixing' something else. It's notably close to that `db.close()` bug in the worker process that we never fully got to the bottom of.

How urgent is this?

**Comment by smit1678** [comment]
Non-critical, just an experience issue for the time being. Will restart and see if that fixes.

**Comment by smit1678** [comment]
Coming back here after figuring out more information. Restarting and rebuilding current master branch didn't fix this. Attempted at running older commits to identify where the bug was introduced and it looks like it was introduced after this commit: https://github.com/hotosm/oam-catalog/commit/1f8ba282a36e228ff7035d748b587e1960e3d206.
