### ISSUE TITLE
Indexing multiple buckets does not happen

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#107]
Current `oauth-login` branch seems to not index multiple buckets. Seeing this on a local docker installation using this [test bucket register](https://gist.github.com/smit1678/3374fd1e467aa9a3a0b8dc6a6aa086c5) which grabs both the `oin-hotosm` and `oin-hotosm-staging` buckets. The indexing seemed to complete on the `oin-hotosm-staging` bucket but did not index any of the files on `oin-hotosm`. 

When testing to try to debug this, first time I was using the environment variable `OIN_BUCKET=oin-hotosm-staging`. This only indexed the `oin-hotosm-staging` bucket. When switching the variable to be `OIN_BUCKET=oin-hotosm`, then it only indexed the `oin-hotosm` bucket. 

I think the correct behavior here should be that the API should index all buckets that are listed in the bucket register. We do need to define environment variables for the OIN_BUCKET, the final bucket for the Uploader workers, but that shouldn't limit what is indexed. 

@tombh Have you seen this behavior?

**Comment by tombh** [comment]
Fix pushed.
