### ISSUE TITLE
AWS endpoint issues around uploading and processing

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#109]
@mojodna Quick summary follow up from our side convo about S3 regions. I didn’t resolve it but it seems to not be blocking so documenting here for others for further follow up. 

*tldr - seems to not matter when you’re deployed on an ec2. A Sydney region ec2 did not have any issues processing and uploading to a Sydney region S3 bucket with the original code.*

Problem: when running locally, we were encountering an issue when using the upload form to S3 buckets not in the us-east-1 region. Items would upload to the temp bucket but not download to be processed. Since our buckets were in the Sydney region, but providing a default path-style endpoint http://s3.amazonaws.com/bucket, it wouldn’t resolve. https://github.com/hotosm/oam-browser/blob/oauth-login/src/components/uploader/home.js#L274-L277

Docs on paths: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

Using a path-style endpoint, you can only use the http://s3.amazonaws.com/bucket endpoint if your bucket is in us east. otherwise you need to use a region-specific endpoint, http://s3-aws-region.amazonaws.com/bucket. Path-style endpoints seem to be easier to factor for since some virtual-style endpoints differ between regions. 

BUT...

When changing the uploader form to use a region-specific path-style, everything processes using the dynamic tiler fine locally, but we encounter errors when trying to upload to the final bucket. I suspect in the same way there was an issue with the uploader form using the wrong endpoint, the tiler is as well. But I couldn’t pin point. It seems to happen here in the process.sh uploading step: [log output](https://gist.github.com/smit1678/4300a5ab3455776cdb69a64155080d10).

Last BUT...

This doesn't seem to matter when you're deployed on an ec2 in the same region. When we deployed on a Sydney region ec2, the url format as it stands now seems to process fine.

**Comment by mojodna** [comment]
Brief thought here: 

> When changing the uploader form to use a region-specific path-style, everything processes using the dynamic tiler fine locally, but we encounter errors when trying to upload to the final bucket. I suspect in the same way there was an issue with the uploader form using the wrong endpoint, the tiler is as well. But I couldn’t pin point. It seems to happen here in the process.sh uploading step: log output.

Setting `AWS_DEFAULT_REGION=<current region>` might address it (and is probably implicit when using AWS tools on EC2 instances).

I'm guessing that `s3.amazonaws.com` resolves locally (when on EC2) to the S3 endpoint in the same region.

Nice that it works on EC2, but we should definitely make it work everywhere.
