### ISSUE TITLE
Use Swagger instead of Apidocs

### ISSUE THREAD

**Issue by tombh** [hotosm/oam-api#111]
See hotosm/OpenAerialMap#86

Swagger has 3 advantages; firstly it has wider suppport, secondly it builds itself from code not comments and thirdly it enforces parameter checking in endpoints. There is already a drop-in plugin: https://github.com/glennjones/hapi-swagger It will simply require that the `validate: { params: {} }` properties on each endpoint are correctly populated.

**Comment by cgiovando** [comment]
Tracking in #154
