### ISSUE TITLE
Message error when Batch job fails

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#123]
When processing an image that fails (like an image that doesn't have a georeference), the message returned (or not returned) breaks the upload status page: 

![openaerialmap browser 2018-01-18 09-56-45](https://user-images.githubusercontent.com/796838/35092006-06db148e-fc36-11e7-9e50-37e79318eaad.png)

**Comment by mojodna** [comment]
I thought i'd added something to the API to default `messages` to `[]`, but it'd be better to check for `== null` in the front-end.

The first status update results in `messages` getting populated.

Or, this is something different, since that's referring to `message`.
