### ISSUE TITLE
Batch ran out of memory when a second job came through

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#129]
![image](https://user-images.githubusercontent.com/796838/38257054-7812c6ae-3757-11e8-99b3-0a6daa68f35b.png)

@mojodna Does the Batch process put a new request into an existing ec2 or does it spin up a new one? Perhaps this was a one off issue that the instance was killed during the middle of processing?

**Comment by mojodna** [comment]
It uses existing instances if any are already running. Docker puts a cap on memory usage (3GB) in addition to that being used as the reservation size.

How large was the source image? (Can you DM me a link?)
