### ISSUE TITLE
CastError: Cast to number failed for value

### ISSUE THREAD

**Issue by smit1678** [hotosm/oam-api#130]
After processing an image, a error is thrown when trying to post the metadata to the mongodb. 

```
api_1         | { CastError: Cast to number failed for value "-64.6317153,2.9E-6,-64.6316475,1.103E-4" at path "bbox" for model "Meta"

```

Happens on [this image](http://195.154.41.149/download/U_001_V1.tif). Within the same image set, [this image](http://195.154.41.149/download/U_005_V1.tif) works. 

[Error log here](https://gist.github.com/smit1678/ab32064e2eb96035ef7b221f4d3695e3).

**Comment by mojodna** [comment]
I can't figure out what would be producing the scientific notation. Based on the logs (and tested output of `rio ...`), it's not input from the transcoder and `bbox.toString()` doesn't serialize like that. The only other thing I can think of is that Mongoose isn't parsing results from MongoDB properly. There've been a lot of releases on the Mongoose 4.x branch (it's on 4.13.2; we're using 4.0.2), so if that's the case, there may have been a fix. I spent some time looking through the [history](https://github.com/Automattic/mongoose/blob/master/History.md) and saw various references to arrays but nothing jumped out at me.

**Comment by smit1678** [comment]
@mojodna Thanks for digging into this. It isn't related to these threads is it?

https://github.com/openimagerynetwork/oin-meta-generator/pull/25

https://github.com/hotosm/oam-uploader-api/issues/42

**Comment by mojodna** [comment]
I don't think so. oin-meta-generator was dropped in favor of https://github.com/mojodna/marblecutter-tools/blob/1c053b924c08f155948d2394fcd4e4ef3f686587/bin/process.sh#L229-L244, the output of which doesn't include `bbox` (it's calculated by `@turf/bbox` in the uploader endpoint).

Are you sure it was that image? `rio shapes` says that the bbox is `[39.287634, -5.74306, 39.313591, -5.719001]`. That could be another clue...

(Also, ignore my comment about Mongoose; we're using `^4.0.2`, thus `4.13.2`.)
