### ISSUE TITLE
Broken Link to further api-information

### ISSUE THREAD

**Issue by a333klm** [hotosm/oam-api#148]
The Link in the readme.md is broken. Where do I find full details of the API endpoints?

![brokenlink](https://user-images.githubusercontent.com/29760462/58366193-fd53c880-7ece-11e9-994c-c58b0a23ce51.PNG)
.

**Comment by TechArtistG** [comment]
What's the deal with this?  @JannisEgelhof  fixed it but looks like some tests have failed? Still broken on the main site.
