### ISSUE TITLE
add a daily dump of mongo data to S3

### ISSUE THREAD

**Issue by scisco** [hotosm/oam-api#47]
Requires a bucket on S3. We will use heroku scheduler to run it on daily basis

**Comment by smit1678** [comment]
Created a backup bucket - `oam-backup` - for this. cc @danielfdsilva

**Comment by scisco** [comment]
@smit1678 @danielfdsilva 
MongoLab supports automated scheduled backups to a S3 bucket. Details are here: http://docs.mongolab.com/backups/

When you enter the MongoLab account from Heroku page, there is a backup tab that supports creating scheduled backups to S3. I need to do is to add the S3 credentials for a bucket.

<img width="1090" alt="screen shot 2015-10-26 at 12 59 11 pm" src="https://cloud.githubusercontent.com/assets/1933118/10736071/743da49c-7be1-11e5-8ac7-aff3653b71fc.png">

**Comment by danielfdsilva** [comment]
Now it seems easy enough. :)
@smit1678 apparently we need a credit card.

**Comment by smit1678** [comment]
@danielfdsilva Thanks for looking into this. Talked it over with @scisco more. We'll just look to set up a twice weekly backup and I think this will suffice. Next action over to me to set that up.
