### ISSUE TITLE
Indexing should retry failures when paginating through buckets

### ISSUE THREAD

**Issue by mojodna** [hotosm/oam-api#86]
I had to run `node worker.js` multiple times in order to fully index the new `oin-hotosm` bucket.

Something (probably the function that paginates through S3, potentially due to unbounded concurrency) fails with:

```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

**Comment by smit1678** [comment]
@mojodna Is this still an issue or was this fixed in https://github.com/hotosm/oam-catalog/pull/93?

**Comment by mojodna** [comment]
Retrying wasn't added, but this error is much less likely to occur with the reduced concurrency. For full resilience, it still probably should be.

**Comment by tombh** [comment]
I've got a funny feeling this is to do with the seemingly errant `db.close()` I asked @kamicut about in #93. If it is, then it's fixed in the unmerged #98.

**Comment by kamicut** [comment]
@tombh no, this was happening before the rewrite in #93.

**Comment by tombh** [comment]
Thanks, so then we have to assume this isn't fixed.

I think the most direct and comprehensive solution here is to move over to using a formal queuing library, such as; [hapi-job-queue](https://github.com/firstandthird/hapi-job-queue), [mongodb-queue](https://github.com/chilts/mongodb-queue) or [monq](https://github.com/scttnlsn/monq). They have already solved the problems we are facing here. This will also further separate our concerns and conform more closely to 12 Factor Apps. Unless there are arguments against this, I will make an issue for it.

**Comment by tombh** [comment]
See #102 for my proposed fix.
