### ISSUE TITLE
Problem with sort query

### ISSUE THREAD

**Issue by yojiyojiyoji** [hotosm/oam-api#95]
There seems some problem with sort query.
(My impression is that default value for 'sort' is not properly set to 'desc'.)
Please try following four URLs to see the problem.

https://oam-catalog.herokuapp.com/meta?order_by=acquisition_end&limit=100 (Problem)
https://oam-catalog.herokuapp.com/meta?sort=asc&order_by=acquisition_end&limit=100 (O.K.)
https://oam-catalog.herokuapp.com/meta?limit=100 (Problem)
https://oam-catalog.herokuapp.com/meta?sort=asc&limit=100 (O.K.)

I've also checked the codes in controllers/meta.js, but do you think following part is correct?

  // Handle custom sorts, starting with default of higher resolution and
  // newer imagery first. Do nothing if we don't have both sort and order_by.
  var sort = { gsd: 1, acquisition_end: -1 };
  if (_.has(payload, 'sort') && _.has(payload, 'order_by')) {
    // Custom sort, overwrite default
    sort = {};
    sort[payload.order_by] = (payload.sort === 'asc') ? 1 : -1;

    // sanitized payload
    payload = _.omit(payload, 'sort');
    payload = _.omit(payload, 'order_by');
  } else if (_.has(payload, 'sort')) {
    // sanitized payload
    payload = _.omit(payload, 'sort');
  } else if (_.has(payload, 'order_by')) {
    // sanitized payload
    payload = _.omit(payload, 'order_by');
  }

**Comment by yojiyojiyoji** [comment]
I think this is not serious issue. I will always send 'desc' or 'asc' query, without using default value.

**Comment by tombh** [comment]
Re-opening this because it does look like a bug on [line 85](https://github.com/hotosm/oam-catalog/blob/902a7ab2a0e95abb7e32aaa6515f91515c85939c/controllers/meta.js#L85):

```js
var sort = { gsd: 1, acquisition_end: -1 };
```

should be:

```js
var sort = { gsd: 1, acquisition_to: -1 };
```
